#!/bin/bash

echo "=========================================="
echo "🚀 Hướng dẫn Chạy Jenkins CI/CD"
echo "=========================================="
echo ""

echo "📌 CÁCH 1: CHẠY DEMO (Không cần Jenkins)"
echo "----------------------------------------"
echo "Chạy pipeline demo để test tất cả components:"
echo ""
echo "  cd /home/admin1/Code/ocr_khai_sinh"
echo "  ./scripts/demo-pipeline.sh"
echo ""
echo "Demo này sẽ:"
echo "  ✓ Checkout code"
echo "  ✓ Build Docker image"
echo "  ✓ Run API tests"
echo "  ✓ Simulate push & deploy"
echo ""

echo "📌 CÁCH 2: SETUP JENKINS THẬT"
echo "----------------------------------------"
echo ""
echo "Bước 1: Cài đặt Jenkins"
echo "  docker run -d --name jenkins -p 8080:8080 \\"
echo "    -v jenkins_home:/var/jenkins_home \\"
echo "    -v /var/run/docker.sock:/var/run/docker.sock \\"
echo "    jenkins/jenkins:lts"
echo ""
echo "Bước 2: Truy cập Jenkins"
echo "  URL: http://localhost:8080"
echo "  Password: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword"
echo ""
echo "Bước 3: Cài plugins"
echo "  - Docker Pipeline"
echo "  - Git"
echo "  - Pipeline"
echo ""
echo "Bước 4: Tạo credentials (Manage Jenkins → Credentials)"
echo "  - docker-hub-credentials (Username/Password)"
echo "  - docker-registry-url (Secret: docker.io)"
echo "  - deploy-host (Secret: your-server-ip)"
echo "  - deploy-user (Secret: your-username)"
echo "  - ssh-deploy-key (SSH Private Key)"
echo ""
echo "Bước 5: Tạo Pipeline Job"
echo "  - New Item → Pipeline"
echo "  - SCM: Git"
echo "  - Repository URL: your-git-repo"
echo "  - Script Path: Jenkinsfile"
echo "  - Save & Build Now!"
echo ""

echo "📌 CÁCH 3: CHẠY TỪNG PHẦN"
echo "----------------------------------------"
echo ""
echo "Test API:"
echo "  python3 tests/test_api.py"
echo ""
echo "Build Docker image:"
echo "  docker build -t ocr-khai-sinh:latest ."
echo ""
echo "Deploy:"
echo "  ./scripts/deploy.sh"
echo ""

echo "=========================================="
echo "📚 XEM THÊM DOCUMENTATION"
echo "=========================================="
echo ""
echo "  Quick Start:    README-CICD.md"
echo "  Setup chi tiết: docs/jenkins-setup.md"
echo "  Kết quả demo:   DEMO-RESULTS.md"
echo ""
